[package]
name = "ingester"
version = "0.1.0"
authors = ["Nga Tran <nga-tran@live.com>"]
edition = "2021"

[dependencies]
arrow = { version = "8.0", features = ["prettyprint"] }
arrow-flight = "8.0"
arrow_util = { path = "../arrow_util" }
base64 = "0.13"
bytes = "1.0"
client_util = { path = "../client_util" }
datafusion = { path = "../datafusion" }
data_types = { path = "../data_types" }
futures = "0.3"
generated_types = { path = "../generated_types" }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch"}
object_store = { path = "../object_store" }
parking_lot = "0.12"
parquet = "8.0"
parquet_file = { path = "../parquet_file" }
predicate = { path = "../predicate" }
prost = "0.9"
query = { path = "../query" }
rand = "0.8.3"
schema = { path = "../schema" }
snafu = "0.7"
thiserror = "1.0"
time = { path = "../time" }
tokio = { version = "1.13", features = ["macros", "parking_lot", "rt-multi-thread", "sync", "time"] }
tonic = { version = "0.6" }
uuid = { version = "0.8", features = ["v4"] }
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
mutable_batch_lp = { path = "../mutable_batch_lp" }
test_helpers = { path = "../test_helpers" }
